# Generated by Django 4.2.3 on 2023-08-16 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isActive',
        ),
        migrations.AddField(
            model_name='listing',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
