# Generated by Django 4.2.3 on 2023-08-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bids',
            name='lister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lister', to='auctions.listing'),
        ),
    ]
