# Generated by Django 4.2.3 on 2023-08-16 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_watchlist_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='lister',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='bidlist',
        ),
        migrations.AddField(
            model_name='bids',
            name='listbid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listbid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='listcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listcomment', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingWatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
