# Generated by Django 4.2.3 on 2023-08-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_newprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newprice',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
