# Generated by Django 4.2.3 on 2023-08-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bidswinners_listwinner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='userbid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listbid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='newprice',
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidprice', to='auctions.bids'),
        ),
    ]
