# Generated by Django 4.2.3 on 2023-08-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_userbid_bids_user_remove_bids_listbid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bidswinners',
        ),
    ]
