# Generated by Django 4.2.3 on 2023-08-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_newprice_alter_listing_price_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='userbid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listbid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bids', to='auctions.bids'),
        ),
    ]
