# Generated by Django 4.2.3 on 2023-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_addbids_alter_listing_price_delete_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
