# Generated by Django 4.2.3 on 2023-08-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='newprice',
        ),
    ]
