# Generated by Django 4.2.3 on 2023-08-17 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='winnerPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnerlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winnerlist', to='auctions.listing')),
                ('winneruser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winneruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
